from langchain_anthropic import ChatAnthropic
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_core.documents import Document
from langchain_community.vectorstores import FAISS

"""
    Sample enterprise documents.
    In real life these would come from CloudWatch, runbooks, Snowflake docs, etc.
    """


def load_documents():
    return [
        Document(
            page_content="""
Glue Job Troubleshooting Guide

If a Glue job fails with AmazonS3Exception Access Denied, check the following:
1. The IAM role has s3:GetObject permission
2. The IAM role has kms:Decrypt permission if the files are encrypted
3. The S3 bucket policy allows the Glue execution role
4. The target S3 path is correct
""".strip(),
            metadata={"source": "runbook_glue_access_denied"},
        ),
        Document(
            page_content="""
Glue Job Memory Troubleshooting

If a Glue job fails with OutOfMemoryError, common causes include:
1. Input partitions are too large
2. Worker type is too small
3. Skewed joins create large executor pressure
4. Caching large DataFrames increases memory usage
""".strip(),
            metadata={"source": "runbook_glue_memory"},
        ),
        Document(
            page_content="""
Snowflake Table Documentation

Table: customer_master

Columns:
customer_id
first_name
last_name
date_of_birth
email
phone_number
customer_status
created_at
updated_at
""".strip(),
            metadata={"source": "snowflake_customer_master"},
        ),
        Document(
            page_content="""
IAM Policy Guidance

Approved Glue execution roles must include:
- s3:GetObject
- s3:ListBucket
- logs:CreateLogGroup
- logs:CreateLogStream
- logs:PutLogEvents
- kms:Decrypt
""".strip(),
            metadata={"source": "iam_policy_glue"},
        ),
        Document(
            page_content="""
Large Operations Guide

For Glue failures involving S3 access issues, investigate IAM permissions,
KMS decrypt access, S3 bucket policy alignment, and recent infrastructure changes.
""".strip(),
            metadata={"source": "operations_guide"},
        ),
    ]

# Step 2: Build embeddings
def build_vector_store(documents):
    embeddings = HuggingFaceEmbeddings(
        model_name="sentence-transformers/all-MiniLM-L6-v2"
    )
    return FAISS.from_documents(documents, embeddings)

# Retrieval Step from vector store
def normal_retrieval(vector_store, question, k=3):
    return vector_store.similarity_search(question, k=k)

# HyDE Step
def generate_hypothetical_document(llm, question):
    """
    HyDE step:
    generate a hypothetical answer-like document for retrieval purposes only.
    """
    prompt = f"""
You are helping a retrieval system.

Write a short hypothetical document that would likely answer the user's question.
Do not write bullet points unless needed.
Write it like a concise internal knowledge base note.

User question:
{question}

Hypothetical document:
""".strip()

    response = llm.invoke(prompt)
    return response.content.strip()

def hyde_retrieval(vector_store, llm, question, k=3):
    hypothetical_doc = generate_hypothetical_document(llm, question)
    retrieved_docs = vector_store.similarity_search(hypothetical_doc, k=k)
    return hypothetical_doc, retrieved_docs

def print_results(title, docs):
    print("\n" + "=" * 100)
    print(title)
    print("=" * 100)
    for i, doc in enumerate(docs, start=1):
        print(f"\n[{i}] Source: {doc.metadata.get('source', 'unknown')}")
        print(doc.page_content)


if __name__ == '__main__':
    documents = load_documents()
    vector_store = build_vector_store(documents)
    llm = ChatAnthropic(model="claude-sonnet-4-20250514")
    question = "Why did my Glue job fail with an access issue this morning?"


    # HyDE retrieval
    hypothetical_doc, hyde_docs = hyde_retrieval(vector_store, llm, question, k=3)
    print("\n" + "=" * 100)
    print("HYPOTHETICAL DOCUMENT GENERATED BY HYDE")
    print("=" * 100)
    print(hypothetical_doc)

    print_results("HYDE RETRIEVAL RESULTS", hyde_docs)
